CREATE TABLE EMPLOYEE_DETAILS
(
      EMPLOYEE_ID INT PRIMARY KEY,
	  FIRST_NAME CHAR(20) NOT NULL,
	  LAST_NAME CHAR(20) NOT NULL,
	  SALARY INT ,
	  DEPARTMENT CHAR(20) NOT NULL
);

INSERT INTO EMPLOYEE_DETAILS(EMPLOYEE_ID, FIRST_NAME , LAST_NAME, SALARY , DEPARTMENT)
VALUES(1 , 'AISH', 'CHANDRASEKARAN', 1200000, 'TECH');

INSERT INTO EMPLOYEE_DETAILS(EMPLOYEE_ID, FIRST_NAME , LAST_NAME, SALARY , DEPARTMENT) 
VALUES(2 , 'ESHA', 'DESWAL', 1200000, 'TECH');

INSERT Into EMPLOYEE_DETAILS(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT)
VALUES(3, 'AMRITH', 'ANAND', 1300000, 'CSE');

INSERT INTO EMPLOYEE_DETAILS(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT)
VALUES(4, 'SRI' , 'LAYA' , 1400000, 'CSE');

INSERT INTO EMPLOYEE_DETAILS(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT)
VALUES(5, 'ANKIT' , 'RAJ' , 1400000, 'CSE');

INSERT INTO EMPLOYEE_DETAILS(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT)
VALUES(6, 'PRINCE' , 'BHAGAT' , 1400000, 'CSE');

SELECT * FROM EMPLOYEE_DETAILS;

SELECT *FROM EMPLOYEE_DETAILS
WHERE FIRST_NAME = 'AISH';

SELECT *FROM EMPLOYEE_DETAILS
WHERE FIRST_NAME LIKE 'A%'; --- TO PRINT THE NAMES STARTS WITH A 

SELECT *FROM EMPLOYEE_DETAILS
WHERE LAST_NAME LIKE '%A%'; ---TO PRINT THE NAMES WHICH HAS A IN MIDDLE


 ----AGGREGATE FUNCTIONS


SELECT MAX(SALARY) FROM EMPLOYEE_DETAILS; --- TO FIND THE MAX SALARY

SELECT MIN(SALARY)FROM EMPLOYEE_DETAILS; ---TO FIND THE MIN SALARY

SELECT COUNT (SALARY)FROM EMPLOYEE_DETAILS; ---TO COUNT THE NUMBER OF ROWS

SELECT AVG(SALARY)FROM EMPLOYEE_DETAILS;--- TI GET THE AVG

--- ASCENDING DESENDING

SELECT * FROM EMPLOYEE_DETAILS 
ORDER BY FIRST_NAME; --- ASCENDING ORDER

SELECT * FROM EMPLOYEE_DETAILS 
ORDER BY FIRST_NAME DESC; ---DESCENDING ORDER

UPDATE EMPLOYEE_DETAILS
SET FIRST_NAME = 'AISHWARYA'
WHERE FIRST_NAME = 'AISH';

SELECT*FROM EMPLOYEE_DETAILS;

UPDATE EMPLOYEE_DETAILS
SET FIRST_NAME = 'SHANTHI'---UPDATE A NEW DETAIL EDIT A DETAIL OF THE EMPLOYEE
WHERE EMPLOYEE_ID = 1;

SELECT*FROM EMPLOYEE_DETAILS;

DELETE FROM EMPLOYEE_DETAILS 
WHERE EMPLOYEE_ID=6;--- DELETE THE ROW OF ENMPLOYEE DETAILS 

SELECT*FROM EMPLOYEE_DETAILS;

